name: ci

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: self-hosted

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: 'Checkout '
        uses: actions/checkout@v2

      - name: 'Setup node env'
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
          cache: npm

      - name: 'Install dependencies'
        run: npm install

      - name: 'Build Project'
        run: npm run build

      - name: 'Genererate Assets'
        run: npm run generate
